export const LOGIN_START = "LOGIN_START";
export const LOGIN_OKAY = "LOGIN_OKAY";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_OKAY = "REGISTER_OKAY";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_POSTS_START = "GET_POSTS_START";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_POSTS_OKAY = "GET_POSTS_OKAY";

export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_OKAY = "UPLOAD_OKAY";
export const UPLOAD_FAIL = "UPLOAD_START";

export const CURRENT_POST = "CURRENT_POST";
export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_OKAY = "ADD_COMMENT_OKAY";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";
export const FETCH_COMMENTS_OKAY = "FETCH_COMMENTS_OKAY";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";

// export const POST_CHANGED = "POST_CHANGED";
// export const POST_NO_CHANGE = "POST_NO_CHANGE";
